export default [
  {
    flag: '🇦🇫',
    countryName: 'Afghanistan (‫افغانستان‬‎)',
    dialCode: '93',
    iso2: 'af',
  },
  { flag: '🇦🇽', countryName: 'Åland Islands', dialCode: '358', iso2: 'ax' },
  {
    flag: '🇦🇱',
    countryName: 'Albania (Shqipëri)',
    dialCode: '355',
    iso2: 'al',
  },
  {
    flag: '🇩🇿',
    countryName: 'Algeria (‫الجزائر‬‎)',
    dialCode: '213',
    iso2: 'dz',
  },
  { flag: '🇦🇸', countryName: 'American Samoa', dialCode: '1', iso2: 'as' },
  { flag: '🇦🇩', countryName: 'Andorra', dialCode: '376', iso2: 'ad' },
  { flag: '🇦🇴', countryName: 'Angola', dialCode: '244', iso2: 'ao' },
  { flag: '🇦🇮', countryName: 'Anguilla', dialCode: '1', iso2: 'ai' },
  { flag: '🇦🇬', countryName: 'Antigua and Barbuda', dialCode: '1', iso2: 'ag' },
  { flag: '🇦🇷', countryName: 'Argentina', dialCode: '54', iso2: 'ar' },
  {
    flag: '🇦🇲',
    countryName: 'Armenia (Հայաստան)',
    dialCode: '374',
    iso2: 'am',
  },
  { flag: '🇦🇼', countryName: 'Aruba', dialCode: '297', iso2: 'aw' },
  { flag: '🇦🇺', countryName: 'Australia', dialCode: '61', iso2: 'au' },
  {
    flag: '🇦🇹',
    countryName: 'Austria (Österreich)',
    dialCode: '43',
    iso2: 'at',
  },
  {
    flag: '🇦🇿',
    countryName: 'Azerbaijan (Azərbaycan)',
    dialCode: '994',
    iso2: 'az',
  },
  { flag: '🇧🇸', countryName: 'Bahamas', dialCode: '1', iso2: 'bs' },
  {
    flag: '🇧🇭',
    countryName: 'Bahrain (‫البحرين‬‎)',
    dialCode: '973',
    iso2: 'bh',
  },
  {
    flag: '🇧🇩',
    countryName: 'Bangladesh (বাংলাদেশ)',
    dialCode: '880',
    iso2: 'bd',
  },
  { flag: '🇧🇧', countryName: 'Barbados', dialCode: '1', iso2: 'bb' },
  {
    flag: '🇧🇾',
    countryName: 'Belarus (Беларусь)',
    dialCode: '375',
    iso2: 'by',
  },
  { flag: '🇧🇪', countryName: 'Belgium (België)', dialCode: '32', iso2: 'be' },
  { flag: '🇧🇿', countryName: 'Belize', dialCode: '501', iso2: 'bz' },
  { flag: '🇧🇯', countryName: 'Benin (Bénin)', dialCode: '229', iso2: 'bj' },
  { flag: '🇧🇲', countryName: 'Bermuda', dialCode: '1', iso2: 'bm' },
  { flag: '🇧🇹', countryName: 'Bhutan (འབྲུག)', dialCode: '975', iso2: 'bt' },
  { flag: '🇧🇴', countryName: 'Bolivia', dialCode: '591', iso2: 'bo' },
  {
    flag: '🇧🇦',
    countryName: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    dialCode: '387',
    iso2: 'ba',
  },
  { flag: '🇧🇼', countryName: 'Botswana', dialCode: '267', iso2: 'bw' },
  { flag: '🇧🇷', countryName: 'Brazil (Brasil)', dialCode: '55', iso2: 'br' },
  {
    flag: '🇮🇴',
    countryName: 'British Virgin Islands',
    dialCode: '1',
    iso2: 'vg',
  },
  { flag: '🇧🇳', countryName: 'Brunei', dialCode: '673', iso2: 'bn' },
  {
    flag: '🇧🇬',
    countryName: 'Bulgaria (България)',
    dialCode: '359',
    iso2: 'bg',
  },
  { flag: '🇧🇫', countryName: 'Burkina Faso', dialCode: '226', iso2: 'bf' },
  {
    flag: '🇧🇮',
    countryName: 'Burundi (Uburundi)',
    dialCode: '257',
    iso2: 'bi',
  },
  {
    flag: '🇰🇭',
    countryName: 'Cambodia (កម្ពុជា)',
    dialCode: '855',
    iso2: 'kh',
  },
  {
    flag: '🇨🇲',
    countryName: 'Cameroon (Cameroun)',
    dialCode: '237',
    iso2: 'cm',
  },
  { flag: '🇨🇦', countryName: 'Canada', dialCode: '1', iso2: 'ca' },
  {
    flag: '🇨🇻',
    countryName: 'Cape Verde (Kabu Verdi)',
    dialCode: '238',
    iso2: 'cv',
  },
  {
    flag: '🇧🇶',
    countryName: 'Caribbean Netherlands',
    dialCode: '599',
    iso2: 'bq',
  },
  { flag: '🇰🇾', countryName: 'Cayman Islands', dialCode: '1', iso2: 'ky' },
  {
    flag: '🇨🇫',
    countryName: 'Central African Republic (République centrafricaine)',
    dialCode: '236',
    iso2: 'cf',
  },
  { flag: '🇹🇩', countryName: 'Chad (Tchad)', dialCode: '235', iso2: 'td' },
  { flag: '🇨🇱', countryName: 'Chile', dialCode: '56', iso2: 'cl' },
  { flag: '🇨🇳', countryName: 'China (中国)', dialCode: '86', iso2: 'cn' },
  { flag: '🇨🇽', countryName: 'Christmas Island', dialCode: '61', iso2: 'cx' },
  {
    flag: '🇨🇨',
    countryName: 'Cocos (Keeling) Islands',
    dialCode: '61',
    iso2: 'cc',
  },
  { flag: '🇨🇴', countryName: 'Colombia', dialCode: '57', iso2: 'co' },
  {
    flag: '🇰🇲',
    countryName: 'Comoros (‫جزر القمر‬‎)',
    dialCode: '269',
    iso2: 'km',
  },
  { flag: '🇨🇰', countryName: 'Cook Islands', dialCode: '682', iso2: 'ck' },
  { flag: '🇨🇷', countryName: 'Costa Rica', dialCode: '506', iso2: 'cr' },
  { flag: '🇨🇮', countryName: 'Côte d’Ivoire', dialCode: '225', iso2: 'ci' },
  {
    flag: '🇭🇷',
    countryName: 'Croatia (Hrvatska)',
    dialCode: '385',
    iso2: 'hr',
  },
  { flag: '🇨🇺', countryName: 'Cuba', dialCode: '53', iso2: 'cu' },
  { flag: '🇨🇼', countryName: 'Curaçao', dialCode: '599', iso2: 'cw' },
  { flag: '🇨🇾', countryName: 'Cyprus (Κύπρος)', dialCode: '357', iso2: 'cy' },
  { flag: '🇩🇰', countryName: 'Denmark (Danmark)', dialCode: '45', iso2: 'dk' },
  { flag: '🇩🇯', countryName: 'Djibouti', dialCode: '253', iso2: 'dj' },
  { flag: '🇩🇲', countryName: 'Dominica', dialCode: '1', iso2: 'dm' },
  {
    flag: '🇩🇴',
    countryName: 'Dominican Republic (República Dominicana)',
    dialCode: '1',
    iso2: 'do',
  },
  { flag: '🇪🇨', countryName: 'Ecuador', dialCode: '593', iso2: 'ec' },
  { flag: '🇪🇬', countryName: 'Egypt (‫مصر‬‎)', dialCode: '20', iso2: 'eg' },
  { flag: '🇸🇻', countryName: 'El Salvador', dialCode: '503', iso2: 'sv' },
  {
    flag: '🇬🇶',
    countryName: 'Equatorial Guinea (Guinea Ecuatorial)',
    dialCode: '240',
    iso2: 'gq',
  },
  { flag: '🇪🇷', countryName: 'Eritrea', dialCode: '291', iso2: 'er' },
  { flag: '🇪🇪', countryName: 'Estonia (Eesti)', dialCode: '372', iso2: 'ee' },
  { flag: '🇸🇿', countryName: 'Eswatini', dialCode: '268', iso2: 'sz' },
  { flag: '🇪🇹', countryName: 'Ethiopia', dialCode: '251', iso2: 'et' },
  {
    flag: '🇫🇰',
    countryName: 'Falkland Islands (Islas Malvinas)',
    dialCode: '500',
    iso2: 'fk',
  },
  {
    flag: '🇫🇴',
    countryName: 'Faroe Islands (Føroyar)',
    dialCode: '298',
    iso2: 'fo',
  },
  { flag: '🇫🇯', countryName: 'Fiji', dialCode: '679', iso2: 'fj' },
  { flag: '🇫🇮', countryName: 'Finland (Suomi)', dialCode: '358', iso2: 'fi' },
  { flag: '🇫🇷', countryName: 'France', dialCode: '33', iso2: 'fr' },
  {
    flag: '🇬🇫',
    countryName: 'French Polynesia (Polynésie française)',
    dialCode: '689',
    iso2: 'pf',
  },
  {
    flag: '🇵🇫',
    countryName: 'French Polynesia (Polynésie française)',
    dialCode: '689',
    iso2: 'pf',
  },
  {
    flag: '🇹🇫',
    countryName: 'French Polynesia (Polynésie française)',
    dialCode: '689',
    iso2: 'pf',
  },
  { flag: '🇬🇦', countryName: 'Gabon', dialCode: '241', iso2: 'ga' },
  { flag: '🇬🇲', countryName: 'Gambia', dialCode: '220', iso2: 'gm' },
  {
    flag: '🇬🇪',
    countryName: 'Georgia (საქართველო)',
    dialCode: '995',
    iso2: 'ge',
  },
  {
    flag: '🇩🇪',
    countryName: 'Germany (Deutschland)',
    dialCode: '49',
    iso2: 'de',
  },
  { flag: '🇬🇭', countryName: 'Ghana (Gaana)', dialCode: '233', iso2: 'gh' },
  { flag: '🇬🇮', countryName: 'Gibraltar', dialCode: '350', iso2: 'gi' },
  { flag: '🇬🇷', countryName: 'Greece (Ελλάδα)', dialCode: '30', iso2: 'gr' },
  {
    flag: '🇬🇱',
    countryName: 'Greenland (Kalaallit Nunaat)',
    dialCode: '299',
    iso2: 'gl',
  },
  { flag: '🇬🇩', countryName: 'Grenada', dialCode: '1', iso2: 'gd' },
  { flag: '🇬🇵', countryName: 'Guadeloupe', dialCode: '590', iso2: 'gp' },
  { flag: '🇬🇺', countryName: 'Guam', dialCode: '1', iso2: 'gu' },
  { flag: '🇬🇹', countryName: 'Guatemala', dialCode: '502', iso2: 'gt' },
  { flag: '🇬🇬', countryName: 'Guernsey', dialCode: '44', iso2: 'gg' },
  { flag: '🇬🇳', countryName: 'Guinea (Guinée)', dialCode: '224', iso2: 'gn' },
  {
    flag: '🇬🇼',
    countryName: 'Guinea-Bissau (Guiné Bissau)',
    dialCode: '245',
    iso2: 'gw',
  },
  { flag: '🇬🇾', countryName: 'Guyana', dialCode: '592', iso2: 'gy' },
  { flag: '🇭🇹', countryName: 'Haiti', dialCode: '509', iso2: 'ht' },
  { flag: '🇭🇳', countryName: 'Honduras', dialCode: '504', iso2: 'hn' },
  { flag: '🇭🇰', countryName: 'Hong Kong (香港)', dialCode: '852', iso2: 'hk' },
  {
    flag: '🇭🇺',
    countryName: 'Hungary (Magyarország)',
    dialCode: '36',
    iso2: 'hu',
  },
  { flag: '🇮🇸', countryName: 'Iceland (Ísland)', dialCode: '354', iso2: 'is' },
  { flag: '🇮🇳', countryName: 'India (भारत)', dialCode: '91', iso2: 'in' },
  { flag: '🇮🇩', countryName: 'Indonesia', dialCode: '62', iso2: 'id' },
  { flag: '🇮🇷', countryName: 'Iran (‫ایران‬‎)', dialCode: '98', iso2: 'ir' },
  { flag: '🇮🇶', countryName: 'Iraq (‫العراق‬‎)', dialCode: '964', iso2: 'iq' },
  { flag: '🇮🇪', countryName: 'Ireland', dialCode: '353', iso2: 'ie' },
  { flag: '🇮🇲', countryName: 'Isle of Man', dialCode: '44', iso2: 'im' },
  { flag: '🇮🇱', countryName: 'Israel (‫ישראל‬‎)', dialCode: '972', iso2: 'il' },
  { flag: '🇮🇹', countryName: 'Italy (Italia)', dialCode: '39', iso2: 'it' },
  { flag: '🇯🇲', countryName: 'Jamaica', dialCode: '1', iso2: 'jm' },
  { flag: '🇯🇵', countryName: 'Japan (日本)', dialCode: '81', iso2: 'jp' },
  { flag: '🇯🇪', countryName: 'Jersey', dialCode: '44', iso2: 'je' },
  {
    flag: '🇯🇴',
    countryName: 'Jordan (‫الأردن‬‎)',
    dialCode: '962',
    iso2: 'jo',
  },
  {
    flag: '🇰🇿',
    countryName: 'Kazakhstan (Казахстан)',
    dialCode: '7',
    iso2: 'kz',
  },
  { flag: '🇰🇪', countryName: 'Kenya', dialCode: '254', iso2: 'ke' },
  { flag: '🇰🇮', countryName: 'Kiribati', dialCode: '686', iso2: 'ki' },
  {
    flag: '🇰🇵',
    countryName: 'North Korea (조선 민주주의 인민 공화국)',
    dialCode: '850',
    iso2: 'kp',
  },
  {
    flag: '🇰🇷',
    countryName: 'South Sudan (‫جنوب السودان‬‎)',
    dialCode: '211',
    iso2: 'ss',
  },
  { flag: '🇽🇰', countryName: 'Kosovo', dialCode: '383', iso2: 'xk' },
  {
    flag: '🇰🇼',
    countryName: 'Kuwait (‫الكويت‬‎)',
    dialCode: '965',
    iso2: 'kw',
  },
  {
    flag: '🇰🇬',
    countryName: 'Kyrgyzstan (Кыргызстан)',
    dialCode: '996',
    iso2: 'kg',
  },
  { flag: '🇱🇦', countryName: 'Laos (ລາວ)', dialCode: '856', iso2: 'la' },
  { flag: '🇱🇻', countryName: 'Latvia (Latvija)', dialCode: '371', iso2: 'lv' },
  {
    flag: '🇱🇧',
    countryName: 'Lebanon (‫لبنان‬‎)',
    dialCode: '961',
    iso2: 'lb',
  },
  { flag: '🇱🇸', countryName: 'Lesotho', dialCode: '266', iso2: 'ls' },
  { flag: '🇱🇷', countryName: 'Liberia', dialCode: '231', iso2: 'lr' },
  { flag: '🇱🇾', countryName: 'Libya (‫ليبيا‬‎)', dialCode: '218', iso2: 'ly' },
  { flag: '🇱🇮', countryName: 'Liechtenstein', dialCode: '423', iso2: 'li' },
  {
    flag: '🇱🇹',
    countryName: 'Lithuania (Lietuva)',
    dialCode: '370',
    iso2: 'lt',
  },
  { flag: '🇱🇺', countryName: 'Luxembourg', dialCode: '352', iso2: 'lu' },
  { flag: '🇲🇴', countryName: 'Macau (澳門)', dialCode: '853', iso2: 'mo' },
  {
    flag: '🇲🇬',
    countryName: 'Madagascar (Madagasikara)',
    dialCode: '261',
    iso2: 'mg',
  },
  { flag: '🇲🇼', countryName: 'Malawi', dialCode: '265', iso2: 'mw' },
  { flag: '🇲🇾', countryName: 'Malaysia', dialCode: '60', iso2: 'my' },
  { flag: '🇲🇻', countryName: 'Maldives', dialCode: '960', iso2: 'mv' },
  { flag: '🇲🇱', countryName: 'Mali', dialCode: '223', iso2: 'ml' },
  { flag: '🇲🇹', countryName: 'Malta', dialCode: '356', iso2: 'mt' },
  { flag: '🇲🇭', countryName: 'Marshall Islands', dialCode: '692', iso2: 'mh' },
  { flag: '🇲🇶', countryName: 'Martinique', dialCode: '596', iso2: 'mq' },
  {
    flag: '🇲🇷',
    countryName: 'Mauritania (‫موريتانيا‬‎)',
    dialCode: '222',
    iso2: 'mr',
  },
  { flag: '🇲🇺', countryName: 'Mauritius (Moris)', dialCode: '230', iso2: 'mu' },
  { flag: '🇾🇹', countryName: 'Mayotte', dialCode: '262', iso2: 'yt' },
  { flag: '🇲🇽', countryName: 'Mexico (México)', dialCode: '52', iso2: 'mx' },
  { flag: '🇫🇲', countryName: 'Micronesia', dialCode: '691', iso2: 'fm' },
  {
    flag: '🇲🇩',
    countryName: 'Moldova (Republica Moldova)',
    dialCode: '373',
    iso2: 'md',
  },
  { flag: '🇲🇨', countryName: 'Monaco', dialCode: '377', iso2: 'mc' },
  { flag: '🇲🇳', countryName: 'Mongolia (Монгол)', dialCode: '976', iso2: 'mn' },
  {
    flag: '🇲🇪',
    countryName: 'Montenegro (Crna Gora)',
    dialCode: '382',
    iso2: 'me',
  },
  { flag: '🇲🇸', countryName: 'Montserrat', dialCode: '1', iso2: 'ms' },
  {
    flag: '🇲🇦',
    countryName: 'Morocco (‫المغرب‬‎)',
    dialCode: '212',
    iso2: 'ma',
  },
  {
    flag: '🇲🇿',
    countryName: 'Mozambique (Moçambique)',
    dialCode: '258',
    iso2: 'mz',
  },
  {
    flag: '🇲🇲',
    countryName: 'Myanmar (Burma) (မြန်မာ)',
    dialCode: '95',
    iso2: 'mm',
  },
  { flag: '🇳🇦', countryName: 'Namibia (Namibië)', dialCode: '264', iso2: 'na' },
  { flag: '🇳🇷', countryName: 'Nauru', dialCode: '674', iso2: 'nr' },
  { flag: '🇳🇵', countryName: 'Nepal (नेपाल)', dialCode: '977', iso2: 'np' },
  {
    flag: '🇳🇱',
    countryName: 'Netherlands (Nederland)',
    dialCode: '31',
    iso2: 'nl',
  },
  { flag: '🇳🇨', countryName: 'New Zealand', dialCode: '64', iso2: 'nz' },
  { flag: '🇳🇿', countryName: 'New Zealand', dialCode: '64', iso2: 'nz' },
  { flag: '🇳🇮', countryName: 'Nicaragua', dialCode: '505', iso2: 'ni' },
  { flag: '🇳🇪', countryName: 'Niger (Nijar)', dialCode: '227', iso2: 'ne' },
  { flag: '🇳🇬', countryName: 'Nigeria', dialCode: '234', iso2: 'ng' },
  { flag: '🇳🇺', countryName: 'Niue', dialCode: '683', iso2: 'nu' },
  { flag: '🇳🇫', countryName: 'Norfolk Island', dialCode: '672', iso2: 'nf' },
  {
    flag: '🇲🇰',
    countryName: 'North Korea (조선 민주주의 인민 공화국)',
    dialCode: '850',
    iso2: 'kp',
  },
  {
    flag: '🇲🇵',
    countryName: 'Northern Mariana Islands',
    dialCode: '1',
    iso2: 'mp',
  },
  { flag: '🇳🇴', countryName: 'Norway (Norge)', dialCode: '47', iso2: 'no' },
  { flag: '🇴🇲', countryName: 'Oman (‫عُمان‬‎)', dialCode: '968', iso2: 'om' },
  {
    flag: '🇵🇰',
    countryName: 'Pakistan (‫پاکستان‬‎)',
    dialCode: '92',
    iso2: 'pk',
  },
  { flag: '🇵🇼', countryName: 'Palau', dialCode: '680', iso2: 'pw' },
  {
    flag: '🇵🇸',
    countryName: 'Palestine (‫فلسطين‬‎)',
    dialCode: '970',
    iso2: 'ps',
  },
  { flag: '🇵🇦', countryName: 'Panama (Panamá)', dialCode: '507', iso2: 'pa' },
  { flag: '🇵🇬', countryName: 'Papua New Guinea', dialCode: '675', iso2: 'pg' },
  { flag: '🇵🇾', countryName: 'Paraguay', dialCode: '595', iso2: 'py' },
  { flag: '🇵🇪', countryName: 'Peru (Perú)', dialCode: '51', iso2: 'pe' },
  { flag: '🇵🇭', countryName: 'Philippines', dialCode: '63', iso2: 'ph' },
  { flag: '🇵🇱', countryName: 'Poland (Polska)', dialCode: '48', iso2: 'pl' },
  { flag: '🇵🇹', countryName: 'Portugal', dialCode: '351', iso2: 'pt' },
  { flag: '🇵🇷', countryName: 'Puerto Rico', dialCode: '1', iso2: 'pr' },
  { flag: '🇶🇦', countryName: 'Qatar (‫قطر‬‎)', dialCode: '974', iso2: 'qa' },
  {
    flag: '🇷🇪',
    countryName: 'Réunion (La Réunion)',
    dialCode: '262',
    iso2: 're',
  },
  { flag: '🇷🇴', countryName: 'Romania (România)', dialCode: '40', iso2: 'ro' },
  { flag: '🇷🇺', countryName: 'Russia (Россия)', dialCode: '7', iso2: 'ru' },
  { flag: '🇷🇼', countryName: 'Rwanda', dialCode: '250', iso2: 'rw' },
  {
    flag: '🇧🇱',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  {
    flag: '🇸🇭',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  {
    flag: '🇰🇳',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  {
    flag: '🇱🇨',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  {
    flag: '🇲🇫',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  {
    flag: '🇵🇲',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  {
    flag: '🇻🇨',
    countryName: 'Saint Vincent and the Grenadines',
    dialCode: '1',
    iso2: 'vc',
  },
  { flag: '🇼🇸', countryName: 'Samoa', dialCode: '685', iso2: 'ws' },
  { flag: '🇸🇲', countryName: 'San Marino', dialCode: '378', iso2: 'sm' },
  {
    flag: '🇸🇹',
    countryName: 'São Tomé and Príncipe (São Tomé e Príncipe)',
    dialCode: '239',
    iso2: 'st',
  },
  {
    flag: '🇸🇦',
    countryName: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    dialCode: '966',
    iso2: 'sa',
  },
  { flag: '🇸🇳', countryName: 'Senegal (Sénégal)', dialCode: '221', iso2: 'sn' },
  { flag: '🇷🇸', countryName: 'Serbia (Србија)', dialCode: '381', iso2: 'rs' },
  { flag: '🇸🇨', countryName: 'Seychelles', dialCode: '248', iso2: 'sc' },
  { flag: '🇸🇱', countryName: 'Sierra Leone', dialCode: '232', iso2: 'sl' },
  { flag: '🇸🇬', countryName: 'Singapore', dialCode: '65', iso2: 'sg' },
  { flag: '🇸🇽', countryName: 'Sint Maarten', dialCode: '1', iso2: 'sx' },
  {
    flag: '🇸🇰',
    countryName: 'Slovakia (Slovensko)',
    dialCode: '421',
    iso2: 'sk',
  },
  {
    flag: '🇸🇮',
    countryName: 'Slovenia (Slovenija)',
    dialCode: '386',
    iso2: 'si',
  },
  { flag: '🇸🇧', countryName: 'Solomon Islands', dialCode: '677', iso2: 'sb' },
  {
    flag: '🇸🇴',
    countryName: 'Somalia (Soomaaliya)',
    dialCode: '252',
    iso2: 'so',
  },
  {
    flag: '🇿🇦',
    countryName: 'South Sudan (‫جنوب السودان‬‎)',
    dialCode: '211',
    iso2: 'ss',
  },
  {
    flag: '🇬🇸',
    countryName: 'South Sudan (‫جنوب السودان‬‎)',
    dialCode: '211',
    iso2: 'ss',
  },
  {
    flag: '🇸🇸',
    countryName: 'South Sudan (‫جنوب السودان‬‎)',
    dialCode: '211',
    iso2: 'ss',
  },
  { flag: '🇪🇸', countryName: 'Spain (España)', dialCode: '34', iso2: 'es' },
  {
    flag: '🇱🇰',
    countryName: 'Sri Lanka (ශ්‍රී ලංකාව)',
    dialCode: '94',
    iso2: 'lk',
  },
  {
    flag: '🇸🇩',
    countryName: 'Sudan (‫السودان‬‎)',
    dialCode: '249',
    iso2: 'sd',
  },
  { flag: '🇸🇷', countryName: 'Suriname', dialCode: '597', iso2: 'sr' },
  {
    flag: '🇸🇯',
    countryName: 'Svalbard and Jan Mayen',
    dialCode: '47',
    iso2: 'sj',
  },
  { flag: '🇸🇪', countryName: 'Sweden (Sverige)', dialCode: '46', iso2: 'se' },
  {
    flag: '🇨🇭',
    countryName: 'Switzerland (Schweiz)',
    dialCode: '41',
    iso2: 'ch',
  },
  { flag: '🇸🇾', countryName: 'Syria (‫سوريا‬‎)', dialCode: '963', iso2: 'sy' },
  { flag: '🇹🇼', countryName: 'Taiwan (台灣)', dialCode: '886', iso2: 'tw' },
  { flag: '🇹🇯', countryName: 'Tajikistan', dialCode: '992', iso2: 'tj' },
  { flag: '🇹🇿', countryName: 'Tanzania', dialCode: '255', iso2: 'tz' },
  { flag: '🇹🇭', countryName: 'Thailand (ไทย)', dialCode: '66', iso2: 'th' },
  { flag: '🇹🇱', countryName: 'Timor-Leste', dialCode: '670', iso2: 'tl' },
  { flag: '🇹🇬', countryName: 'Togo', dialCode: '228', iso2: 'tg' },
  { flag: '🇹🇰', countryName: 'Tokelau', dialCode: '690', iso2: 'tk' },
  { flag: '🇹🇴', countryName: 'Tonga', dialCode: '676', iso2: 'to' },
  { flag: '🇹🇹', countryName: 'Trinidad and Tobago', dialCode: '1', iso2: 'tt' },
  { flag: '🇹🇳', countryName: 'Tunisia (‫تونس‬‎)', dialCode: '216', iso2: 'tn' },
  { flag: '🇹🇷', countryName: 'Turkey (Türkiye)', dialCode: '90', iso2: 'tr' },
  { flag: '🇹🇲', countryName: 'Turkmenistan', dialCode: '993', iso2: 'tm' },
  {
    flag: '🇹🇨',
    countryName: 'Turks and Caicos Islands',
    dialCode: '1',
    iso2: 'tc',
  },
  { flag: '🇹🇻', countryName: 'Tuvalu', dialCode: '688', iso2: 'tv' },
  { flag: '🇺🇬', countryName: 'Uganda', dialCode: '256', iso2: 'ug' },
  { flag: '🇺🇦', countryName: 'Ukraine (Україна)', dialCode: '380', iso2: 'ua' },
  { flag: '🇦🇪', countryName: 'United States', dialCode: '1', iso2: 'us' },
  { flag: '🇬🇧', countryName: 'United States', dialCode: '1', iso2: 'us' },
  { flag: '🇺🇸', countryName: 'United States', dialCode: '1', iso2: 'us' },
  { flag: '🇺🇲', countryName: 'United States', dialCode: '1', iso2: 'us' },
  { flag: '🇺🇾', countryName: 'Uruguay', dialCode: '598', iso2: 'uy' },
  {
    flag: '🇺🇿',
    countryName: 'Uzbekistan (Oʻzbekiston)',
    dialCode: '998',
    iso2: 'uz',
  },
  { flag: '🇻🇺', countryName: 'Vanuatu', dialCode: '678', iso2: 'vu' },
  {
    flag: '🇻🇦',
    countryName: 'Vatican City (Città del Vaticano)',
    dialCode: '39',
    iso2: 'va',
  },
  { flag: '🇻🇪', countryName: 'Venezuela', dialCode: '58', iso2: 've' },
  { flag: '🇻🇳', countryName: 'Vietnam (Việt Nam)', dialCode: '84', iso2: 'vn' },
  {
    flag: '🇻🇬',
    countryName: 'British Virgin Islands',
    dialCode: '1',
    iso2: 'vg',
  },
  { flag: '🇻🇮', countryName: 'United States', dialCode: '1', iso2: 'us' },
  {
    flag: '🇼🇫',
    countryName: 'Wallis and Futuna (Wallis-et-Futuna)',
    dialCode: '681',
    iso2: 'wf',
  },
  {
    flag: '🇪🇭',
    countryName: 'Western Sahara (‫الصحراء الغربية‬‎)',
    dialCode: '212',
    iso2: 'eh',
  },
  { flag: '🇾🇪', countryName: 'Yemen (‫اليمن‬‎)', dialCode: '967', iso2: 'ye' },
  { flag: '🇿🇲', countryName: 'Zambia', dialCode: '260', iso2: 'zm' },
  { flag: '🇿🇼', countryName: 'Zimbabwe', dialCode: '263', iso2: 'zw' },
] as CountryWithFlag[];

export interface CountryWithFlag {
  flag: string;
  countryName: string;
  dialCode: string;
  iso2: string;
}
